services:
  app:
    image: smdmim/comatching3_be-app:latest
    ports:
      - "40010:8080"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${SPRING_REDIS_PASSWORD} --port 6379
    volumes:
      - redis-data:/data  # Redis 볼륨 추가
    networks:
      - backend

networks:
  backend:

volumes:
  mysql-data:  # MySQL 볼륨
  redis-data:  # Redis 볼륨
