version: '3.9'

services:
  app:
    ports:
      - "40010:8080"
    volumes:
      - prod_app_logs:/app/logs

  mysql:
    ports:
      - "40000:3306"
    volumes:
      - prod_mysql_data:/var/lib/mysql

  redis:
    ports:
      - "40001:6379"
    volumes:
      - prod_redis_data:/dataz

volumes:
  prod_mysql_data:
  prod_redis_data:
  prod_app_logs:
