#version: '3.9'

services:
  app:
    container_name: prod-comatching-be-app
    ports:
      - "40010:8080"
      - "5672:5672"
    volumes:
      - prod_app_logs:/app/logs

  mysql:
    container_name: prod-mysql
    ports:
      - "40000:3306"
    volumes:
      - prod_mysql_data:/var/lib/mysql

  redis:
    container_name: prod-redis
    ports:
      - "40001:6379"
    volumes:
      - prod_redis_data:/data

volumes:
  prod_mysql_data:
  prod_redis_data:
  prod_app_logs:
