services:
  app:
    image: smdmim/comatching3_be-app:latest
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    networks:
      - comatching_be_prod

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - comatching_be_prod

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${SPRING_REDIS_PASSWORD} --port 6379
    volumes:
      - redis-data:/data  # Redis 볼륨 추가
    networks:
      - comatching_be_prod

networks:
  comatching_be_prod:
    name: comatching_be_prod
    external: true

volumes:
  mysql-data:  # MySQL 볼륨
  redis-data:  # Redis 볼륨
